### ISSUE TITLE
[Bug] Paperclip Server fails to start: postgres npm package incompatible with embedded-postgres 15+

### ISSUE THREAD

**Issue by Larsbuilds** [paperclipai/paperclip#4839]
## Bug Description

The Paperclip Server fails to start due to a PostgreSQL protocol incompatibility between the `postgres` npm package (v3.4.8-3.4.9) and `embedded-postgres` (v15.17.0+ and v18.1.0+).

## Error

```
PostgresError: invalid message format
  at ErrorResponse (postgres/src/connection.js:815:30)
  code: '08P01'
  file: 'pqformat.c'
  line: '640'
  routine: 'pq_getmsgend'
```

## Environment

- **Paperclip Version:** 0.3.1 (latest from main branch, commit 3494e84a)
- **Node Version:** 20.20.0
- **OS:** Ubuntu 24.04 (Hetzner VM)
- **Installation Method:** Built from source using pnpm

## Steps to Reproduce

1. Clone the Paperclip repository
2. Run `pnpm install`
3. Build all packages: `pnpm run build`
4. Start the server: `cd server && node dist/index.js`
5. Server attempts to initialize embedded PostgreSQL
6. Server crashes with "invalid message format" error during migration execution

## Root Cause Analysis

The `postgres` npm package (used by Paperclip) has a protocol incompatibility with PostgreSQL 15+:

- **packages/db/package.json** specifies:
  - `"postgres": "^3.4.5"` (currently resolves to 3.4.8-3.4.9)
  - `"embedded-postgres": "^18.1.0-beta.16"` (uses PostgreSQL 18)

- The `postgres` npm client library hasn't been updated to support the wire protocol changes introduced in PostgreSQL 15+

## Attempted Solutions

1. ✅ **Downgraded embedded-postgres to 15.17.0-beta.17** - Same error (PG 15 also incompatible)
2. ✅ **Upgraded postgres to 3.4.9** - Same error
3. ❌ **Tried external PostgreSQL 16** - Same error
4. ❌ **Attempted rebuild** - TypeScript errors due to duplicate drizzle-orm installations

## Additional Context

When upgrading `postgres` to 3.4.9, pnpm creates duplicate `drizzle-orm` installations (one for each postgres version), causing TypeScript compilation errors:

```
Types have separate declarations of a private property 'shouldInlineParams'
```

## Suggested Fix

Consider one of these approaches:

1. **Switch to `pg` package** - The `pg` (node-postgres) package has better PostgreSQL 16+ support
2. **Pin embedded-postgres to PostgreSQL 14** - Use an older PostgreSQL version compatible with `postgres` npm
3. **Update postgres npm** - Wait for/contribute to `postgres` npm package to support PG 15+
4. **Add compatibility layer** - Implement a protocol adapter

## Impact

- ❌ Paperclip Server cannot be started from source
- ❌ Custom adapters (like Ollama) cannot be used (CLI doesn't support custom adapters)
- ✅ Paperclip CLI still works (uses different database setup)

## Related

- postgres npm package: https://github.com/porsager/postgres
- PostgreSQL protocol changes: https://www.postgresql.org/docs/release/15.0/
- Error code 08P01: Protocol violation
- Similar issue #828: Embedded PostgreSQL fails in unprivileged LXC containers
- Similar issue #2703: ERR_MODULE_NOT_FOUND: Cannot find module packages/db/src/client.js
